name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v2

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: Wendell-Ribeiro # Substitua pelo seu username do GitHub
          outputs: dist/snake.svg

      - name: Enviar resultado para o repositório
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
